### ISSUE TITLE
trying to open a folder/file path results in an error

### ISSUE THREAD

**Issue by Kyr4l** [flathub/io.github.cboxdoerfer.FSearch#4]
![image](https://user-images.githubusercontent.com/24955106/230795869-5b22e638-c2cf-4dc8-8e23-fadd0ede0d28.png)

pic rel, it says "Launch failed" whenever i try to open a folder path

**Comment by cboxdoerfer** [comment]
This means the system wasn't able to launch your file manager. What's the output of `gio mime inode/directory`?

**Comment by Kyr4l** [comment]
> This means the system wasn't able to launch your file manager. What's the output of `gio mime inode/directory`?

`12:06:24 (kyral@kdes)-[~] 
(0)-$ gio mime inode/directory
Default application for “inode/directory”: com.vscodium.codium.desktop
Registered applications:
        com.vscodium.codium.desktop
        git-cola-folder-handler.desktop
        org.kde.dolphin.desktop
        org.kde.dolphinsu.desktop
        org.kde.gwenview.desktop
        org.kde.kate.desktop
Recommended applications:
        com.vscodium.codium.desktop
        git-cola-folder-handler.desktop
        org.kde.dolphin.desktop
        org.kde.dolphinsu.desktop
        org.kde.gwenview.desktop
        org.kde.kate.desktop
`

**Comment by Kyr4l** [comment]
for some reason dolphin was on top of the priorities in KDE settings but it didn't work as expected, i moved vscodium at the bottom to fix this

**Comment by cboxdoerfer** [comment]
Ok, so I assume you are using KDE and ideally want to have Dolphin as your default file manager? Currently the system is configured to use VS Codium as your file manager. You can change it to Dolphin with:

`gio mime inode/directory org.kde.dolphin.desktop`

Does this also fix the issue in FSearch?

**Comment by Kyr4l** [comment]
yep it's fixed
![image](https://user-images.githubusercontent.com/24955106/231130889-52f9baea-3769-41a8-ac36-fc0a9c729323.png)
